name: navigator
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^4.0.0
  latlong2: ^0.8.2
  geolocator: ^9.0.2
  flutter_polyline_points: ^1.0.0
  cloud_firestore: ^4.5.0
  firebase_core: ^2.14.0
  arcore_flutter_plugin: ^0.1.0
  ar_flutter_plugin: ^0.7.3
  vector_math: ^2.1.4
  provider: ^6.1.2
  location: ^7.0.0
  flutter_tts: ^4.0.2
  http: ^0.13.6
  permission_handler: ^10.4.5
  glass_kit: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/models/model.glb
   

