name: location_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  geolocator: 9.0.2

  vector_math: ^2.1.4
  collection: ^1.17.1 
  firebase_auth: ^5.1.3
  location: ^7.0.0
  flutter_map: ^4.0.0
  latlong2: ^0.8.2
  cloud_firestore: ^5.2.1
  arcore_flutter_plugin: ^0.1.0 
  firebase_core: ^3.3.0
  uuid: ^4.4.2
 
  # tflite: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
